### GET request to example server
GET http://localhost:8085

###
GET http://localhost:8085/api/students
###
GET http://localhost:8085/api/students/1
###
DELETE http://localhost:8085/api/students/1
###
POST http://localhost:8085/api/students
Content-Type: application/json

{
  "firstName": "Jamila",
  "lastName": "Pidr",
  "email": "jamila@gmail.com",
  "titleBachelor": "informational scurity"
}

###
PUT http://localhost:8085/api/students/3
Content-Type: application/json

{
  "firstName": "Mircea",
  "lastName": "Pidr",
  "email": "jamila@gmail.com",
  "titleBachelor": "Cryptocurrency"
}